'use strict';

module.exports = {
	collapseBooleanAttributes: true,
	collapseWhitespace: true,
	decodeEntities: true,
	html5: true,
	includeAutoGeneratedTags: false,
	minifyCSS: true,
	minifyJS: true,
	processConditionalComments: true,
	quoteCharacter: `"`,
	removeComments: true,
	removeEmptyAttributes: true,
	removeRedundantAttributes: true,
	removeScriptTypeAttributes: true,
	removeStyleLinkTypeAttributes: true,
	trimCustomFragments: true,
	useShortDoctype: true
};
